### ISSUE TITLE
Frontend: Present ethicality score and EULA summary

### ISSUE THREAD

**Issue by stephanie-phuong-khanh** [cs130-w21/22#10]
## User Story
As an end user of this application, I would like the interface to return the ethicality score and summary of my uploaded EULA document so that I can know the estimated ethicality of the agreement I may sign and understand the document through a clear and concise summary.

## Detailed Description
Using [React](https://reactjs.org/), we will parse the response of our API, which would contain an ethicality score from 0% to 100% (or from 0 to 1) with explained description and confidence in our score. The API also returns a summary of the EULA document, which the user can also read to gain clearer understanding of the text. Ideally, the summary would be bullet pointed and the score is presented in a color-coded, visually pleasing manner that is easy to understand.

## Acceptance Criteria
- [x] Given the backend API returns an ethicality score, then the frontend should present the score and the score's confidence in a clear and readable way.
- [x] Given the backend API returns a summary of the EULA document, then the frontend should present this text to the user in bullet points or short paragraphs with simple language, which saves the user time otherwise spent on reading the lengthy EULA.

## Task List
- [x] Ethicality score presentation #46 
- [x] EULA summary presentation #47
- [x] Style output box to match hi-fi mockups #48
- [x] Calculating screen #49
