### ISSUE TITLE
Hi-fi mockups of user interface

### ISSUE THREAD

**Issue by stephanie-phuong-khanh** [cs130-w21/22#13]
## User Story
As an end user of this application, I would like to have an intuitive and aesthetically pleasing interface when using this web application so that I can easily navigate and make use of this EULA score and summary generator.

## Detailed Description
Figma will be used to produce mockups of the user interface, which for now includes screens for either text input of file upload of the EULA, loading during the calculation my the ML model and backend, and intuitive presentation of the ethicality score and document summary.

## Acceptance Criteria
- [x] Given **the text input option is selected**, then **the user should be able to paste their EULA document into the app**.
- [x] Given **the upload file input option is selected**, then **the user should be able to upload a file from their computer**.
- [x] Given **a file is uploading to the app**, then **there should be a bar showing progress of the upload**.
- [x] Given **a request has been sent to calculate EULA score and summary**, then **the user should see a loading animation**.
- [x] Given **the EULA score and summary has been returned from the backend**, then **the user should be given an intuitive presentation of the score, confidence interval, and summary**.

## Task List
- [x] Logo, font, and color scheme for recognizable branding of application #14
- [x] Hi-fi design of screen for text input and file upload #15
- [x] Hi-fi design of screen for loading #16
- [x] Hi-fi design of screen for score and summary presentation #17
