### ISSUE TITLE
Frontend: Input user flow

### ISSUE THREAD

**Issue by stephanie-phuong-khanh** [cs130-w21/22#21]
## User Story
As an end user of the application, I would like to be able to select between pasting the text of my EULA or uploading a PDF version so that I can intuitively provide the input needed for calculation.

## Detailed Description
Using React, we will implement the design and logic to either paste text into an input box or upload a file from the user's computer. The upload should be accompanied by a progress bar of the upload process.

## Acceptance Criteria
- [x] Given **the text input option is selected**, then **the user should be able to paste their EULA document into the app**.
- [x] Given **the upload file input option is selected**, then **the user should be able to upload a file from their computer**.
- [x] Given **a file is uploading to the app**, then **there should be a bar showing progress of the upload**.
- [x] Given **text has been pasted or a file has been upload**, then **the CALCULATE button should be able to be pressed**, but it should not be pressable otherwise.

## Task List
- [x] Frontend skeleton layout #32
- [x] Tabs for selecting input method: text or file #22
- [x] Text input box component #23
- [x] Logic for pressability of calculate button #25
- [x] Implement styling to match hi-fi mockups #26
