### ISSUE TITLE
Frontend: Link backend to frontend

### ISSUE THREAD

**Issue by stephanie-phuong-khanh** [cs130-w21/22#27]
## User Story
As an end user of the application, I would like to be able to successfully send input to the backend and retrieve the response so that I can gain understanding of my EULA document.

## Detailed Description
With the frontend and backend components of this application build, we will test and ensure that the API calls to the backend are successful, with typical functionality, errors, and edge cases handled.

## Acceptance Criteria
- [x] Given **correctly formatted input**, then **the backend should return a score and summary in no longer than three minutes**.
- [x] Given **incorrect input**, then **an error message should be returned and displayed to the user**.
- [x] Given **a failure by the backend to generate score and summary**, then **an error message should be communicated to the user**.

## Task List
- [x] File upload progress bar #50
- [x] Send text input to backend #51
- [x] Send PDF file to backend #52
- [x] Receive and display response from backend #53
- [x] Handle errors from backend #54
- [x] Calculating screen logic #55
