### ISSUE TITLE
Get refined EULA summaries

### ISSUE THREAD

**Issue by DakshIdnani** [cs130-w21/22#28]
## User Story
As a user of the deep learning module, I would like my neural net to accept EULA text and provide more refined text summaries with relatively few errors.

## Detailed Description
I want the deep learning module to process the EULA text data and reduce it into a a **high quality** text summary. 

## Acceptance Criteria
- [x] Given EULA text, the library produces EULA summaries with few syntactic and semantic errors.
- [x] The EULA summaries should sum up the key points of the EULA.

## Task list
- [x] Tune summarizer architecture and hyperparameters #43.
