### ISSUE TITLE
EULA Summarizer User Interface

### ISSUE THREAD

**Issue by daniel145** [cs130-w21/22#4]
## Epic
Description and User Benefit:
Build front-end web application for end users to utilize our application to upload their EULA document and receive a score of its ethicality and summary of its content.

User Actions:
The end user should be able to upload the EULA PDF file from his/her machine or paste the document text into an input box. 
The end user should be able to click a button and in under a minute, retrieve a score of his/her EULA's ethicality and summary.

### Sprint 1
- [x] story #13: Hi-fi mockups of user interface
- [x] story #21: Input user flow
### Sprint 2
- [x] story #10: Present ethicality score and EULA summary 
- [x] story #27: Link backend to frontend
- [x] story #29: Styling finishes and responsiveness
- [x] story #45: Testing
