### ISSUE TITLE
Generate EULA Summary

### ISSUE THREAD

**Issue by DakshIdnani** [cs130-w21/22#5]
## User Story
As a user of the deep learning module, I would like a neural net to accept EULA text and provide a text summary so that I can present those results to users of my backend library.

## Detailed Description
I want the deep learning module to process the EULA text data and reduce it into a concise text summary. I can then serve this summary to users of my backend API.

The deep learning module can be trained by taking a pretrained Bert model and finetuning it on EULA data from a public dataset. The trained model can then serve user queries.

## Acceptance Criteria
- [x] Given EULA text, the library produces a concise yet comprehensive summary of the text with a small number of errors or missed points.

## Task list
- [x] Fine tune pretrained summarizer on EULA dataset #41.
- [x] Deploy summarizer for inference #42.
