### ISSUE TITLE
Generate Ethicality Score

### ISSUE THREAD

**Issue by bruceleung2** [cs130-w21/22#7]
## User Story
As a user of the deep learning module, I would like a neural net to accept EULA text and provide an "ethical or not ethical" score so that I can serve this score to a user of my backend API.

## Detailed Description
I want the deep learning module to process the EULA text data and reduce it into a binary score reflecting if the EULA contains anything unethical or not. I can then serve this signal to users of my backend API.

The deep learning module can be trained by taking a pretrained Bert model and finetuning it on EULA data from a public dataset. The trained model can then serve user queries.

## Acceptance Criteria
- [x] Given the EULA is ethical, then the received score should be "ethical".
- [x] Given the EULA is unethical, the received score should be "unethical".

## Task list
- [x] Preprocess EULA dataset #18 
- [x] Build and train EULA ethicality classifier #19 
- [x] Deploy neural net for inference #20
